### ISSUE TITLE
`brew` causes  ":unneeded is deprecated!"  warning

### ISSUE THREAD

**Issue by wzhliang** [weibeld/k1s#10]
I am seeing the following message when executing `brew` commands, like  `brew uninstall` or `brew uninstall`

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the weibeld/core tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/weibeld/homebrew-core/Formula/k1s.rb:7
```

Not sure what's going on but opening an ticket here as recommended by brew.

**Comment by weibeld** [comment]
Thanks for pointing this out. The deprecated `bottle :unneeded` caused the installations to fail.

It's fixed now in the [formula repository](https://github.com/weibeld/homebrew-core).
