### ISSUE TITLE
fails with MacOS sed

### ISSUE THREAD

**Issue by torstenwerner** [weibeld/k1s#2]
GNU sed works correctly when extracting the port number:

```
$ sed 's/.*:\([0-9]\+\)\b.*/\1/' <<<'Starting to serve on 127.0.0.1:56083'
56083
```

But the MacOS sed fails:
```
$ sed 's/.*:\([0-9]\+\)\b.*/\1/' <<<'Starting to serve on 127.0.0.1:56083'
Starting to serve on 127.0.0.1:56083
```

I have no idea why it fails. But it makes the tool unusable on MacOS at the moment.

**Comment by weibeld** [comment]
Good point. I had already installed GNU sed on my Mac, so I didn't run into this. I will address this issue shortly.

**Comment by weibeld** [comment]
I just fixed it, and both versions of sed should now be supported: https://github.com/weibeld/k1s/blob/64d3cb72bddac913e219061f53e8db26707f5bbb/k1s

Please check if this version now works on your system.

The problem with the above command was the `\b` escape sequence and there was another issue with the two sed commands with the `-i` option, which has also been fixed..

**Comment by torstenwerner** [comment]
Yes the sed call works now. 
But I have a different problem now – probably some issue with my cluster. I'll check that later.
