### ISSUE TITLE
Can support `context`?

### ISSUE THREAD

**Issue by clhlc** [weibeld/k1s#5]
hi ;
   In sometimes , nead to monitoring some k8s cluster,
   if k1s support context like--> k1s --context k8s-cluster

**Comment by weibeld** [comment]
You can set the context in the normal way, for example, with kubectl:

```bash
kubectl config use-context k8s-cluster
```

Or use a tool like [kubectx](https://github.com/ahmetb/kubectx).

After that, k1s will use the cluster corresponding to the context that you selected.
