### ISSUE TITLE
jq: error (at <stdin>:1): Cannot index number with string "object"

### ISSUE THREAD

**Issue by v0112358** [weibeld/k1s#7]
Hello,

Thank you for usefull tool. I am having an issue when run your tool. Jq can't parse output from k1s. Which jq version are you using ?

My jq version: 1.6

The error message:
```
jq: error (at <stdin>:1): Cannot index number with string "object"
parse error: Invalid numeric literal at line 1, column 9
```

**Comment by weibeld** [comment]
I also use jq version 1.6. I never encountered this error. Can you give some more information in which situation this error occurs?

**Comment by v0112358** [comment]
Thanks for your help. I have reinstalled oh-my-zsh theme and everything works fine. The error message above is related to oh-my-zsh theme.
